# -*- coding: utf-8 -*-
"""pandas class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IgCQDV7LUaX32bYLBdxxn3LwphmyP093
"""

import pandas as pd

df = pd.read_csv('pokemon_data.csv')

print(df)

rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

print(df.describe())

print(df.head(10))

print(df.Name[3:5])

print(df.loc[4][4])

print(df.sort_values(["Type 1", "Type 2"], ascending=[1,0]))

print(df.columns.tolist())

print(df.Name)

# prompt: data types of columns type1 and type2

print(df['Type 1'].dtype)
print(df['Type 2'].dtype)

print(df.head(10))

print(df.loc[5])

# prompt: print(df.loc[10].Name) but also .HP

print(df.loc[10, 'Name'])
print(df.loc[10, 'HP'])

# prompt: Print the "pokemon_data" DataFrame based on the "Type 1" column in alphabetical orde

print(df.sort_values('Type 1'))

# prompt: Print top 5 Pokemon with the highest "Attack" stats after sorting?

df_sorted = df.sort_values('Attack', ascending=False)

print(df_sorted[['Name', 'Attack']].head(5))

print(df.sort_values(['Generation', 'Speed'], ascending=[1,0]))

print(df.sort_values('Defense', ascending=0).head(10))