# -*- coding: utf-8 -*-
"""python_mongodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JoJ0Y3pu9_56dC-FUB_MdS7OcP5xPU8T

**import lib to communicate with mongodb**
"""

! python -m pip install pymongo

"""**create connection with MongoDB**"""

import pymongo
from pymongo import MongoClient

# Connect to mongodb db
uri = 'mongodb+srv://ranpar:abcd1234@cluster0.1cpka.mongodb.net/test'
#uri = [copy the connection string from MongoDB]
# start client to connect to MongoDB server
client = MongoClient( uri )

"""**Create Database and Collection**"""

db = client["mydatabase"]

# Create a new collection named "mycollection"
db.create_collection("mycollectionNEW")

# check if the collection is created
print(db.list_collection_names())

"""**list all databases in server**"""

client.list_database_names()

"""**Get Collections from Database - Create ITC_Students DB and Students collections manually**"""

db = client["ITC_Students"]

mycollectoions = db.list_collection_names()
for col in mycollectoions:
    print(col)

"""Get Documents from the Collection"""

collection = db["Students"]

documents = collection.find()
for document in documents:
    print(document)

"""Inert Document to the Collection"""

document = {'_id': '012345678', 'Student_first_name': 'Ran', 'Student_last_name': 'Partush', 'student_birth_date': '1972-12-11'}

collection.insert_one(document)

# Run a querys
documents = collection.find().limit(5)
for document in documents:
  print(document)

"""**Update document in the collection**"""

filter = {"_id": "012345678"}
new_values = {"$set": {"Student_first_name": "Ron"}}
collection.update_one(filter, new_values)

documents = collection.find().limit(5)
for document in documents:
  print(document)

"""**Lets print it all in more human way**"""

collection = db["Students"]

s=""
documents = collection.find().limit(5)
for document in documents:
  for key, value in document.items():
    if key != "_id":
      s+=value +", "
  print(s)
  s=""

collection = db["Students"]

documents = collection.find()
for document in documents:
    print(document)

# prompt: print a dictionary that each row is a month and has another children that says how many students are born in each month. we should have 2 children in this dictionary, one called "month" with the value and one called "count" with the value

collection = db["Students"]

month_dict = {}

for document in list(collection.find()):
    month = document["student_birth_date"].split("-")[1]
    if month not in month_dict:
        month_dict[month] = 0
    month_dict[month] += 1

print(month_dict)

result = []

for month, count in month_dict.items():
    result.append({
        "month": month,
        "count": count
    })

print(result)